### ISSUE TITLE
error.log

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/privacy-framework#16] opened 2018-05-04 13:07 UTC
the error log that joomla creates contains ip addresses

although it is still debatable if an ip address on its own is personally identifiable information we should err on the side of caution - we are not lawyers

so we should have a method to clear the log after a set period of time. 

it is trivial to write a plugin to delete the log file every x days

however you would probably need to keep the last x days of logs so the best way to approach it would be to have some form of log rotation and then only delete the oldest file.

the other alternative would be to only keep x number of lines (records) but that wouldnt satisfy the date requirmeent

**Comment by brianteeman** [comment] 2018-05-04 13:32
yes i think it would have to be using the log rotation method and with a plugin (dont really want to use cron unless it is essential)

Shouldnt be too hard to do that

**Comment by sandewt** [comment] 2018-05-04 15:44
I try to understand the problem, hence the following suggestion:

The `Session Data Purge plugin` uses a function, which is based on the `probability`.
May be you can also use this functionality here too, to do the log rotation check with a plugin? 
So that it will not take place with every request.

```
public function onAfterDispatch()
{
	$probability = $this->params->get('gc_probability', 1);
	$divisor     = $this->params->get('gc_divisor', 100);

	$random = $divisor * lcg_value();

	if ($probability > 0 && $random < $probability)
	{
		$this->doLogRotation();
	}
}	
```

**Comment by mbabker** [comment] 2018-05-04 15:59
For this case a log rotation plugin could run based on a timestamp (similar to the update notification plugin and how it sends emails out).  Because realistically you want log files to rotate out every X days, not every X requests (which would mean several times per day).

**Comment by brianteeman** [comment] 2018-05-04 16:31
I will work on this over the weekend

**Comment by brianteeman** [comment] 2018-05-04 18:55
If you are writing to the file every day then you have something wrong

**Comment by tonypartridge** [comment] 2018-05-04 18:56
😂 I’m not, but some people will be.... just a thought and an easy way to maintain it?

**Comment by PhoenixUK** [comment] 2018-05-04 19:58
@brianteeman 

> although it is still debatable if an ip address on its own is personally identifiable information we should err on the side of caution - we are not lawyers

Just to hopefully place a little meat on the bones above if I may (I'm not a lawyer but read on but heavily invested in Data & Cyber Security incl Privacy / GDPR for Third Sector orgs)

**1.** Firstly here is the link to a law firms PDF on various aspects surrounding Identifiability and GDPR, it is dated 2016 but is one of the best found on this subject, from an actual law firm.

[https://www.slaughterandmay.com/media/2535637/personal-data-anonymisation-and-pseudonymisation-under-the-gdpr.pdf](url)

Page 2 (Bottom but please read all this section) - they state;

>  Online Identifiers - The GDPR explains that online identifiers "may leave traces which, in particular when combined with unique identifiers and other information received by the servers, may be used to create profiles of the individuals and identify them"

**2.** Secondly, read Page 3 - **"Does the GDPR really introduce 'New' categories of personal data?"** and pay attention to the **Online Identifier** section

**3.** Next, [https://www.whitecase.com/publications/alert/court-confirms-ip-addresses-are-personal-data-some-cases](url) is the low down on the Breyer case itself, that SlaughterandMay allude to in the first link.

4. Finally a good summary taking into account both of the above can be found here [https://www.out-law.com/en/articles/2016/march/treating-ip-addresses-as-personal-data-is-best-approach-for-businesses-says-expert-/](url)

**5.** Therefore, would it be possible, feasible or neither - to look to implement partial anonymisation on the IP Addresses contained within a Joomla framework error log?

**6.** Regarding the recent comments from you all above - How does a 'Log Rotation' solution assist Joomla backend end-users, such as Dev's, Site Admins etc to make their site's Error Log IP Addresses 'NEVER' identifiable? I just want to be clear, as I'm not a developer or programmer like a lot of you, so please don't take offence at this question. 

**Summary:**

I think that it is important to point out that, we all know that it's still a relatively 'Grey' area at present and until there are some court cases brought against businesses post 25th of this month - regarding Identifiability and IP Addresses, Joomla as a collective and organisation ought to see IP Addresses as being Identifiable in most cases and look to cover off with xyz solutions in the core where possible.

The reason for this in my mind, is that the risks to Joomla as an organisation and the future reputation of it going forward, could well down the supply chain become embroiled in any IP Address related lawsuits, if it sits back to see if this part of Data Privacy, is challenged by any of the country regulator's, or it is found during any legal action that a decision was taken by those involves, to wait and see kind of thing.

That's why I think it is really important to go forward with caution, than flying by the seat of Joomla's pants as the saying goes.

I look forward to anybody's replies and further thoughts to my comments above.

Regards,

**Comment by brianteeman** [comment] 2018-05-04 20:06
Re point 6
You can never ever use anything on the internet without your IP address being logged

**Comment by PhoenixUK** [comment] 2018-05-04 20:33
Of course Brian, I could have said that indeed but I wanted somebody more invested in the framework than I to.

However, I asked that particular point I suppose to reinforce my thoughts or rest of the comments above about the need, feasibility or possible chances of the Log File containing partially anonymised IP addresses - you could call this a middle ground in the overall grey area of IP addresses and Privacy requirements.

**Comment by brianteeman** [comment] 2018-05-04 20:41
No you can call it what it is which is a misunderstanding of how the internet works. I will not write code to anonynise an ip address. That's just plain crazy.

**Comment by tonypartridge** [comment] 2018-05-04 20:44
I agree with @brianteeman . people in the less tech world have caught onto the IP address as if it’s the sole way the person connects to the internet as if it’s the persons passport and I don’t think they fully grasp how an IP address is used and how quickly they change and can be changed. It just allows identifying the user for a very short period in most scenarios unless there is a fixed IP in place of course.

**Comment by PhoenixUK** [comment] 2018-05-04 20:56
@brianteeman Wrong Brian but let's not turn this into an unpleasant contribution. 

Additionally, you have assumed that I have asked 'You' to write such code, I haven't at all - this is just a discussion and was a contribution based purely on part of your opening comment at the start. 

You are in part accepting of "Erring on the side of caution", that's truly great but I can't see in a court of law, how Rotating or even dumping the log every X period of time will stand up to be honest with you and yet, your dismissive reply doesn't just affect yourself or those within Joomla; remember - the organisation and it's very decisions in such a Privacy Framework will live or die by the implementations put in place for the wider user base, which isn't small is it = increased risks if done incorrectly.

@tonypartridge Granted for e.g. GDPR in areas has been, as largely is often the case with 'Suits', over dramatised and incorrectly positioned, for some of the reasons that you state. However, are you both 'Seriously' being so dismissive, just because there are other routes to spoof IP addresses and so forth?

Also, a short period is all that is required but I am sure that you are acutely aware of that too.

**Comment by mbabker** [comment] 2018-05-04 21:04
If it is really going to come down to it I'd rather turn off the default IP logging in the API than deal with IP sanitization or anonymization.  Fact is the subject is still way too murky to make any sane decisions because every country/law/lawyer are interpreting it all differently.  By the time the IP gets to Joomla it's already going through other systems we CANNOT control.

**Comment by brianteeman** [comment] 2018-05-04 21:14
the day that apache stops logging ip addresses I will write the code for joomla not to
the day that isps stop logging ip addresses I will write the code for joomla not to
the day that the internet is rewritten not to log ip addresses I will write the code for joomla not to

This is not about anonymising the internet

**Comment by PhoenixUK** [comment] 2018-05-04 21:17
@mbabker I don't disagree with your sentiment and therefore the full impacts on Joomla's Framework and people's use of it would be what exactly - what in the teams knowledge would be lost, if it was turned off?

Personally, I have never needed to use the IP addresses within J's log file, to solve any form of error or issue but then, I am totally accepting that just because I haven't doesn't mean other people using J haven't had that need.

**Comment by brianteeman** [comment] 2018-05-04 21:24
One thing in that log will be failed attempts to login to your web site. So you would need the ip address in order to block it. That is exactly why the internet logs ip addresses and is the legitimate use that the regulations require. The reason to rotate the logs and delete the old ones is because by then you no longer have a legitimate use to keep them. (you should have already blocked those ip addresses for example by then)

I am sorry but you are completely misunderstanding what these regulations are about. they are not about anonymising your usage of the internet at all. If you want to be anonymous on the internet then that is a personal decision and nothing to do with the gdpr regulations (or any similar regulations in other countries)

Joomla has no obligation at all when it comes to data privacy - it is just a tool. It is supplied to you with no warranty at all

**Comment by PhoenixUK** [comment] 2018-05-04 21:24
Could a Poll be run on the J website and Social Media channels to ask the very question regarding researching the impact on the wider community users of J, if Default IP Logging was disabled going forward and see what the community results in.

Whilst this wouldn't be the full picture, it would be a more democratic approach before going ahead and choosing one or the other?

**Comment by brianteeman** [comment] 2018-05-04 21:31
I wasnt aware this was a democracy

**Comment by mbabker** [comment] 2018-05-04 21:47
No we are not going to run a poll.  Having a global configuration to not log IPs by default will break extensions needlessly.  It is either an all or nothing approach and the cases where logs are actually be written fall under legitimate use cases per law, so rotation and enabling removal of old data continues enabling compliance.

If someone really wants the logging system to anonymize or exclude IPs plugins can handle this.

**Comment by PhoenixUK** [comment] 2018-05-04 22:34
I can now see for a fact that it isn't @brianteeman 

It seems very much a closed shop and 'clique' and not for me on this basis - no loss you will no doubt think after this.

Why does the organisation put out a request for all manner of contributor's from various backgrounds, if something is put forward it is automatically shot down in an instant.

It would seem that those who control the framework, incl code etc clearly don't 'want' to implement what enough of the incoming privacy law(s) either state(s) or infer(s) is required - atleast until such a case comes before the courts and suits the exact nature being spoken about here. Instead, seemingly preferring to put it's X number of global end-users at risk of their own possible legal case fights in the future, through a handful of people's cynicism and apathy and more.

Great work!

**Comment by mbabker** [comment] 2018-05-04 22:49
We can't blindly sanitize/anonymize IPs from logs because there valid cases for including them in log entries that would be impossible with a sanitization routine.  Yes, the handling of IP addresses is an issue; no, it is not an issue we are in a position to adequately address.

This is a case where owners are going to be more diligent about checking logs for potentially sensitive data (as GitHub and Twitter have pointed out the hard way this week).  IP address processing will be something to be disclosed through the reporting system planned, so users won't be blissfully unaware, but I also believe it is too early to take any action that will impede legitimate actions on the data.

**Comment by tonypartridge** [comment] 2018-05-05 05:59
It’s not like that at all, please don’t feel that because one of your concerns isn’t addressed.

This privacy component/plugin is designed to meet GDPR issues, which are not related to anonymity of IP addresses as such. Removal of them when a user requests account deletion yes, but not to make them anonymous by default.

Your input is very valuable and appreciated.

Noting, I am just a user/developer of Joomla too who has had plenty of good ideas turned down especially by @brianteeman 😂.

**Comment by brianteeman** [comment] 2018-05-06 09:11
@mbabker I am assuming that the "logrotation" should be done for both the logs created by the System - User Log" and the "System - Debug" plugins.

The "logration" could therefore be done as a new plugin or the code added to each of these existing plugins. 

Your advice please

**Comment by mbabker** [comment] 2018-05-06 14:41
Unless there's going to be an issue with extensions which actually parse the log files and display them in the backend, I'd just have the rotation mechanism update all PHP files in the `log_path` configured directory.  There are more than those two plugins generating logs:

- Core updates
- Smart Search indexing
- Media Manager uploads

What makes this more interesting is you can customize the logger so that IP addresses are NOT logged (I also just found out that all uses of this config param in core, and my own extension code, is all wrong; `$options['format']` should be `$options['text_entry_format']`).  If we [did this right](https://github.com/joomla-projects/privacy-framework/blob/8c033ce919334f8e8c6fcca422bef9b87a53a7ff/administrator/components/com_joomlaupdate/controllers/update.php#L30-L32) then the core update log wouldn't include IPs.

**Comment by brianteeman** [comment] 2018-05-06 19:16
So are you staying it should be one plugin that rotates all logs in the folder

**Comment by mbabker** [comment] 2018-05-06 19:16
Yes.

**Comment by brianteeman** [comment] 2018-05-06 19:31
System-LogRotate it is

**Comment by dirigit** [comment] 2018-05-11 04:34
@PhoenixUK Sad enough I must share your opinion about interest of full implementation of privacy over here. I already mentioned it in another thread as well some days ago.

Neither @brianteeman nor @mbabker seem to be really aware that there are very stable and constant IP addresses for users in many countries. Especially with IP v6 there is almost no change.

Legal obligation to have IP addresses of visitors at hand for some time (i.e. three months) is another kind of animal. This has to be managed  at server side and is not task of an application like a CMS.

Privacy at application level means that no application holds private data with information about visitors to be able to build profiles. IP addresses are part of such a profile for sure.  In case user logs in it's very interesting how many and which IP addresses he is using. After having several address at hand he could be identified with high probability even as guest user.

There is absolut no relation to anonymous usage of internet - the opposite applies due to technical requirenments.

To give a little example from real live (I loose anonymity for this):
I've two different providers for internet access. Both offer IP v4 and IP v6. Both accounts didn't change IP addresses (IP v4 and v6) within last 14 months at least.

I.e. at github one can identify me since long time whenever IP address is logged and at hand for somebody. One can build a profile about my interests over here very easy.

Means: There is no privacy in case a front end application like a CMS is logging IP addresses and somebody is working with it. In case one get's user's IP addresses at some site he can build a cross reference to every other system when having access to those data at other systems.

This is where GDPR and similar regulations are part of the game:
It doesn't matter for being logged on or not at any system - one can identify everybody and watch what actions user is performing. A personal profile can be build, not to mention identification of person for itself.

And: Capability to build profiles this way hits the heart of advertising industry - they have a real problem.

There is need of "privacy by design". Either application (i.e. CMS) being used supports it or user (admin) of application (i.e. CMS) most probably is in a very bad position in some cases.

cu, diri

**Comment by brianteeman** [comment] 2018-05-11 09:42
https://www.whitecase.com/publications/alert/court-confirms-ip-addresses-are-personal-data-some-cases

**Comment by tonypartridge** [comment] 2018-05-11 09:48
Exactly as Brian points out, in the link. It’s only personal data if you have other data associated with it. Otherwise you know it’s someone but not who. Dg41 if you switch off your router over night and fire it up In The morning it will likely be different unless it’s a dedicated ip. If you want to make your self anonymous then just switch your router off nightly. Hey presto in this case.

It could be an option we refactor and remove the ip’s associated with that user though?

**Comment by mbabker** [comment] 2018-05-11 11:52
If we went with the privacy by design flow being suggested here and arbitrarily anonymized IP addresses, this would prevent ANY capability at the application level from doing ANYTHING related to IP addresses.  Imagine if Joomla sanitized all server/request variables that contained IP information, there is a check in Joomla's session API to ensure that a session cannot be hijacked from a user with another IP address and if IP information was anonymized/sanitized this security measure would not be available.  This is unacceptable.

So no, Joomla is NOT going to blindly anonymize IP addresses in any way.  IP addresses MUST be available within the application to allow legitimate use cases to be actioned.  It is Joomla's responsibility to ensure that the core uses for IP addresses are within that realm of legitimate use cases and that we provide the tools needed to review and purge that information; that is what this effort is focused on, not anonymizing the internet or visitors to all Joomla websites.

**Comment by dirigit** [comment] 2018-05-12 05:00
@mbabker 
Technical view of hijacking a session:

You have cable to access internet?
There are cable providers offering accounts being based on IP v6 only. To save IP v4 addresses they offer IP v4 translation via DS-Lite (DualStack Lite). It's no real dual stack which offers IP v4 AND IP v6 addresses the same time.

To some extend DS-Lite works fine from user to internet. From somewhere to user it doesn't work - it's a oneway street. I.e. VPNs or applications running online have problems. Solutions are available but, they are not casual user's darling.

Problem caused by DS-Lite related to Joomla, Office 365 or whatever:
In case there is no traffic caused by user IP v4 tunnel will be closed. A new tunnel will be opened when user performs some action.

The new tunnel will have another IP v4 address with probability of almost 100 % (I never got same IP v4 address again when testing it for some months) - every trivial session check being based on IP v4 will fail than. Timeout of tunnel depends on provider ...

That's technical reality :(

cu, diri

**Comment by brianteeman** [comment] 2018-05-12 07:56
That has nothing to do with privacy!!!

**Comment by brianteeman** [comment] 2018-05-21 10:14
i have removed the in progress label as i am over committed right now and wont be able to do this.

the idea was to every 30 days
1. delete any file in the logs folder matching 1.name
2. rename any remaining files to 1.name

This way we will always have 60 days of logs available

**Comment by schnuti** [comment] 2018-05-26 10:54
@mbabker @brianteeman 
I now have a plug in half working. 2 questions and 1 problem.
a. What system event would be the best (technically and for the user response time)? onAfterRespond?
b. I was thinking of writing a message to a log file. "Log files rotated" + time.  Which logfile? I have e.g a jcontroller log.
c. It's not easy to test. I have problems with the plug in running more than once. Is the table blocking as in updatenotification a secure way? I use that. I have to debug to find out more.

**Comment by sandewt** [comment] 2018-05-26 12:04
@mbabker , @brianteeman , @schnuti , @alikon 

Speaking of chance, I now see that several people are working on the same plugin independently of each other. 👍 

See also #51

**Comment by schnuti** [comment] 2018-05-26 14:49
@sandewt Thanks for the "Keep eyes open". I checked @alikons 51 and it's almost the same. Nice way to learn.   😃  I may have some comments later.  I have another plug-in to work on in my pipeline.

**Comment by alikon** [comment] 2018-06-08 17:33
can we close this one as we have #61

**Closed** 2018-06-08 17:35 UTC
